name    'jhoblitt-zeromq'
version '0.3.0'

author 'Joshua Hoblitt <jhoblitt@cpan.org>'
license 'Apache'
project_page 'https://github.com/jhoblitt/puppet-zeromq'
source 'https://github.com/jhoblitt/puppet-zeromq.git'
summary 'Manages the zeromq and czmq packages'
description 'Manages the zeromq and czmq packages'
dependency 'puppetlabs/stdlib', '>= 3.0.0'
