name    'jhoblitt-zeromq'
version '0.0.1'

author 'Joshua Hoblitt <jhoblitt@cpan.org>'
license 'Apache'
project_page 'https://github.com/jhoblitt/puppet-zeromq'
source 'https://github.com/jhoblitt/puppet-zeromq.git'
summary 'module skeleton'
description 'module skeleton'
dependency 'puppetlabs/stdlib', '>= 3.0.0'
